Repository ethersphere/swarm-guide, pull requests merged in 2018-06, with the labels that each got.

#82 Extend encryption chapter
  contents/encryption.rst
Labels: ready for review

#87 ens, installation chapters: general improvements
  contents/ens.rst
  contents/installation.rst
Labels: ready for review

#69 Correct information and simplify examples in getting started
  contents/gettingstarted.rst
  contents/introduction.rst
Labels: bug, enhancement, ready for review

#86 architecture chapter fixes
  contents/architecture.rst
Labels: enhancement, ready for review

#91 Extended bzz schemes part with examples
  contents/urlschemes.rst
Labels: ready for review

#93 Overall overhaul and restructure of chapters
  contents/apireference.rst
  contents/architecture.rst
  contents/gettingstarted.rst
  contents/index.rst
  contents/introduction.rst
  contents/pss.rst
  contents/resources.rst
  contents/up-and-download.rst
  contents/usage.rst
  contents/usage/bzz.rst
  contents/usage/encryption.rst
  contents/usage/ens.rst
  contents/usage/fuse.rst
  contents/usage/manifests.rst
  contents/usage/mru.rst
Labels: ready for review

#52 Docs overhaul
  .gitignore
  README.md
  contents/_static/theme_overrides.css
  contents/apireference.rst
  contents/architecture.rst
  contents/conf.py
  contents/configuration.rst
  contents/gettingstarted.rst
  contents/img/bmt.png
  contents/img/chunk.png
  contents/img/dapp-page.svg
  contents/img/distance.svg
  contents/img/dpa-chunking.svg
  contents/img/kademlia.svg
  contents/img/storage-layer.svg
  contents/img/swarm-intro.svg
  contents/img/swarm.png
  contents/img/syncing-high-level.svg
  contents/img/topology.svg
  contents/index.rst
  contents/installation.rst
  contents/introduction.rst
  contents/pss.rst
  contents/resources.rst
  contents/runninganode.rst
  contents/simpleuser.rst
  contents/up-and-download.rst
  contents/usage.rst
  contents/usage/bzz.rst
  contents/usage/encryption.rst
  contents/usage/ens.rst
  contents/usage/fuse.rst
  contents/usage/manifests.rst
  contents/usage/mru.rst
  img-src/dapp-page.odg
  img-src/distance.odg
  img-src/dpa-chunking.odg
  img-src/kademlia.odg
  img-src/storage-layer.odg
  img-src/swarm-intro.odg
  img-src/syncing-high-level.odg
  img-src/topology.odg
Labels: in progress

#96 update code to use correct var
  contents/usage/mru.rst
Labels: ready for review

#98 redocumented configuration params, small refinements to intro section
  contents/configuration.rst
  contents/introduction.rst
Labels: ready for review

#104 Doc fixes aron june28
  contents/gettingstarted.rst
  contents/up-and-download.rst
Labels: ready for review
